backend:
  name: github
  repo: syntaxrecall/syntaxrecall
  branch: master

media_folder: public/images/uploads
public_folder: /images/uploads
publish_mode: editorial_workflow

collections:
  - name: topics
    label: Topics
    folder: content
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date, valueType: string }
      - { name: keywords, label: Keywords, widget: list }
      - { name: body, label: Body, widget: markdown }
    sortable_fields: ['date', 'title', 'commit_date']
